//! HTML Report Generation
//!
//! Generates single-file HTML dashboards with embedded SVG charts.

use crate::report::Report;

/// Generate HTML report (single-file with embedded CSS/JS/SVG)
pub fn generate_html_report(report: &Report) -> String {
    let mut html = String::with_capacity(64 * 1024);

    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("  <meta charset=\"UTF-8\">\n");
    html.push_str("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str(&format!(
        "  <title>FluxBench Report - {}</title>\n",
        report.meta.timestamp.format("%Y-%m-%d")
    ));

    // Embedded CSS
    html.push_str("  <style>\n");
    html.push_str(EMBEDDED_CSS);
    html.push_str("  </style>\n");
    html.push_str("</head>\n<body>\n");

    // Header
    html.push_str("  <header>\n");
    html.push_str("    <h1>FluxBench Report</h1>\n");
    html.push_str(&format!(
        "    <div class=\"meta\">\n      <span>Commit: {}</span>\n      <span>Branch: {}</span>\n      <span>{}</span>\n    </div>\n",
        report.meta.git_commit.as_deref().unwrap_or("unknown"),
        report.meta.git_branch.as_deref().unwrap_or("unknown"),
        report.meta.timestamp.format("%Y-%m-%d %H:%M:%S UTC")
    ));
    html.push_str("  </header>\n");

    // Summary
    html.push_str("  <main>\n");
    html.push_str("    <section id=\"summary\">\n");
    html.push_str("      <h2>Summary</h2>\n");
    html.push_str(&format!(
        "      <div class=\"stats-grid\">\n        <div class=\"stat passed\">{} Passed</div>\n        <div class=\"stat failed\">{} Failed</div>\n        <div class=\"stat crashed\">{} Crashed</div>\n        <div class=\"stat skipped\">{} Skipped</div>\n      </div>\n",
        report.summary.passed,
        report.summary.failed,
        report.summary.crashed,
        report.summary.skipped
    ));
    html.push_str("    </section>\n");

    // Results table
    html.push_str("    <section id=\"results\">\n");
    html.push_str("      <h2>Benchmark Results</h2>\n");
    html.push_str("      <table class=\"results-table\">\n");
    html.push_str("        <thead><tr><th>Benchmark</th><th>Mean</th><th>p99</th><th>Status</th></tr></thead>\n");
    html.push_str("        <tbody>\n");

    for result in &report.results {
        let mean = result.metrics.as_ref().map(|m| format!("{:.2} ns", m.mean_ns)).unwrap_or_else(|| "-".to_string());
        let p99 = result.metrics.as_ref().map(|m| format!("{:.2} ns", m.p99_ns)).unwrap_or_else(|| "-".to_string());
        html.push_str(&format!(
            "          <tr><td>{}</td><td>{}</td><td>{}</td><td>{:?}</td></tr>\n",
            result.id, mean, p99, result.status
        ));
    }

    html.push_str("        </tbody>\n");
    html.push_str("      </table>\n");
    html.push_str("    </section>\n");
    html.push_str("  </main>\n");

    // Footer
    html.push_str(&format!(
        "  <footer><p>Generated by FluxBench v{}</p></footer>\n",
        env!("CARGO_PKG_VERSION")
    ));
    html.push_str("</body>\n</html>\n");

    html
}

const EMBEDDED_CSS: &str = r#"
    :root {
      --bg-primary: #ffffff;
      --bg-secondary: #f5f5f5;
      --text-primary: #333333;
      --accent: #3b82f6;
      --success: #22c55e;
      --warning: #f59e0b;
      --error: #ef4444;
    }
    body { font-family: system-ui, sans-serif; margin: 0; padding: 20px; background: var(--bg-primary); }
    header { margin-bottom: 20px; }
    h1 { margin: 0 0 10px 0; }
    .meta { color: #666; font-size: 14px; }
    .meta span { margin-right: 20px; }
    .stats-grid { display: flex; gap: 20px; margin: 20px 0; }
    .stat { padding: 20px; border-radius: 8px; font-weight: bold; }
    .stat.passed { background: #dcfce7; color: #166534; }
    .stat.failed { background: #fee2e2; color: #991b1b; }
    .stat.crashed { background: #fef3c7; color: #92400e; }
    .stat.skipped { background: #e5e7eb; color: #374151; }
    .results-table { width: 100%; border-collapse: collapse; }
    .results-table th, .results-table td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    .results-table th { background: var(--bg-secondary); }
    footer { margin-top: 40px; color: #666; font-size: 12px; }
"#;
